### ISSUE TITLE
Incorrect default argument?

### ISSUE THREAD

**Issue by james-smith-za** [ska-sa/katsdpsigproc#72]
https://github.com/ska-sa/katsdpsigproc/blob/e55b1b0d6711400d591119858c4309eb430ef7ff/doc/user/examples/triple.py#L17

I tried running this example code but got the following traceback:
```
Traceback (most recent call last):
  File "triple.py", line 19, in <module>
    program = ctx.compile(SOURCE)
  File "/home/jsmith/p3v/lib/python3.6/site-packages/katsdpsigproc/cuda.py", line 140, in compile
    module = pycuda.compiler.SourceModule(source, options=NVCC_FLAGS + extra_flags)
TypeError: can only concatenate list (not "NoneType") to list
```
Granted, I modified the kernel to be a CUDA one instead of an OpenCL one - but I doubt this should have made a difference.

I got it to run by changing the line to `program = ctx.compile(SOURCE, extra_flags=[])`.

This leads me to think that the default `None` argument should actually be an empty list?

Edit: This arose mostly due to me going through the documentation, but perhaps it might be a deeper underlying issue. I can probably implement the fix myself, but it may break things?

**Comment by james-smith-za** [comment]
I see now that changing this explicitly to CUDA did cause (i.e. unearth) the problem, as I had to remove the lambda passed to `create_some_context` - I only had CUDA devices.
